# Generated by Django 3.2.7 on 2022-02-21 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.UUIDField(default=uuid.uuid4)),
                ('weight', models.FloatField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('sender', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('addr_ship_from', models.CharField(max_length=255)),
                ('addr_ship_to', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
