# Generated by Django 3.2.7 on 2022-02-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20220221_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptwrite',
            old_name='to',
            new_name='_to',
        ),
    ]
