# Generated by Django 3.2.7 on 2022-02-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20220222_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptwrite',
            name='city_destination',
            field=models.PositiveIntegerField(default=114),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptwrite',
            name='city_origin',
            field=models.PositiveIntegerField(default=114),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptwrite',
            name='postal_destination',
            field=models.PositiveIntegerField(default=80223),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptwrite',
            name='postal_origin',
            field=models.PositiveIntegerField(default=80223),
            preserve_default=False,
        ),
    ]
