# Generated by Django 3.2.7 on 2022-02-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20220222_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptinstance',
            name='confirmation_url',
            field=models.TextField(default='localhost:8000/confirm'),
        ),
    ]
