# Generated by Django 3.2.7 on 2022-02-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_remove_receiptinstance_confirmation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptinstance',
            name='service_code',
            field=models.CharField(default='YES', max_length=255),
        ),
    ]
