# Generated by Django 3.2.7 on 2022-02-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_receiptinstance_service_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptwrite',
            name='phone_destination',
            field=models.CharField(default='08577987890', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptwrite',
            name='phone_sender',
            field=models.CharField(default='08900908909', max_length=16),
            preserve_default=False,
        ),
    ]
