# Generated by Django 3.2.7 on 2022-02-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20220222_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptwrite',
            name='service_code',
            field=models.CharField(default='YES', max_length=255),
        ),
    ]
